#
# Copyright © 2016-2018 The Thingsboard Authors
# Modifications © 2017-2018 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if and .Values.spark.enabled .Values.spark.s3connector.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.spark.s3connector.name }}-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.spark.s3connector.name }}-app
    spec:
      containers:
      - name: {{ .Values.spark.s3connector.name }}-app
        image: {{ .Values.spark.s3connector.image }}
        securityContext:
          privileged: true
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws
              key: accesskey
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws
              key: secretkey
        - name: S3_BUCKET
          value: {{ .Values.spark.s3connector.s3bucket }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.spark.s3connector.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    k8s-app: {{ .Values.spark.s3connector.name }}-app
{{- end }}