/**
 * Copyright © 2017-2018 Hashmap, Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.hashmapinc.server.extensions.api.plugins.msg;

import com.hashmapinc.server.common.data.id.CustomerId;
import com.hashmapinc.server.common.data.id.DeviceId;

import java.io.Serializable;
import java.util.UUID;

/**
 * The basic interface for messages that are sent from particular rule to plugin
 * instance
 * 
 * @author ashvayka
 *
 */
public interface RuleToPluginMsg<V extends Serializable> extends Serializable {
    
    /**
     * Returns the unique identifier of the message
     * 
     * @return unique identifier of the message.
     */
    UUID getUid();

    
    /**
     * Returns the unique identifier of the device that send the message
     * 
     * @return unique identifier of the device.
     */
    DeviceId getDeviceId();

    /**
     * Returns the unique identifier of the customer that owns the device
     *
     * @return unique identifier of the device.
     */
    CustomerId getCustomerId();

    /**
     * Returns the serializable message payload.
     * 
     * @return the serializable message payload.
     */
    V getPayload();

    /**
     * Returns new instance of message with delivery id generated by akka persistence
     *
     * @param deliveryId generated internally by AtLeastOnceDeliveryActor
     * @return New Instance of message with delivery id
     */
    RuleToPluginMsg<V> copyDeliveryId(Long deliveryId);

    /**
     * Return delivery id which will act as correlation id
     *
     * @return delivery id
     */
    Long getDeliveryId();
}
