#
# Copyright © 2016-2018 The Thingsboard Authors
# Modifications © 2017-2018 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
appVersion: 5.0.1
description: Apache Kafka is publish-subscribe messaging rethought as a distributed
  commit log.
home: https://kafka.apache.org/
icon: https://kafka.apache.org/images/logo.png
keywords:
- kafka
- zookeeper
- kafka statefulset
maintainers:
- email: faraaz@rationalizeit.us
  name: faraazkhan
- email: marc.villacorta@gmail.com
  name: h0tbird
- email: ben@spothero.com
  name: benjigoldberg
name: kafka
sources:
- https://github.com/kubernetes/charts/tree/master/incubator/zookeeper
- https://github.com/Yolean/kubernetes-kafka
- https://github.com/confluentinc/cp-docker-images
- https://github.com/apache/kafka
version: 0.13.5
