{{- if not .Values.csi.enable }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.secretName }}
  namespace:  {{ .Values.api.secretNamespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  # apiAddress: {{ printf "http://%s:%.0f" .Values.service.name .Values.service.externalPort | b64enc | quote }}
  apiAddress: {{ default "" .Values.api.address | b64enc | quote }}
  apiUsername: {{ default "" .Values.api.username | b64enc | quote }}
  apiPassword: {{ default "" .Values.api.password | b64enc | quote }}

{{- end }}

---

# This secret is used to set the initial credentials of the node container.
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.initSecretName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "kubernetes.io/storageos"
data:
  username: {{ default "" .Values.api.username | b64enc | quote }}
  password: {{ default "" .Values.api.password | b64enc | quote }}
