apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.service.internalPort }}
      targetPort: {{ .Values.service.externalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "storageos.name" . }}
    release: {{ .Release.Name }}
    kind: daemonset
