#
# Copyright © 2016-2018 The Thingsboard Authors
# Modifications © 2017-2018 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.cassandra.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempus-data.fullname" . }}-{{ .Values.cassandra.name }}
  labels:
    app: {{ .Values.cassandra.name }}
spec:
  ports:
    - port: 9042
      name: cql
  clusterIP: None
  selector:
    app: {{ .Values.cassandra.name }}
---
apiVersion: "apps/v1beta1"
kind: StatefulSet
metadata:
  name: {{ include "tempus-data.fullname" . }}-{{ .Values.cassandra.name }}
spec:
  serviceName: {{ include "tempus-data.fullname" . }}-{{ .Values.cassandra.name }}
  replicas: {{ .Values.cassandra.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.cassandra.name }}
{{- if .Values.cassandra.affinity }}        
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - {{ .Values.cassandra.name }}
              topologyKey: "kubernetes.io/hostname"  
{{- end }}                    
    spec:
      containers:
      - name: {{ .Values.cassandra.name }}
        image: "{{ .Values.cassandra.image.repository }}:{{ .Values.cassandra.image.tag }}"
        imagePullPolicy: {{ .Values.cassandra.image.pullPolicy }}
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9160
          name: thrift
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        env:
          - name: MAX_HEAP_SIZE
            value: 2048M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "{{ include "tempus-data.fullname" . }}-{{ .Values.cassandra.name }}-0.{{ include "tempus-data.fullname" . }}-{{ .Values.cassandra.name }}.{{ .Release.Namespace }}.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: {{ .Values.cassandra.env.cassandraClusterName }}
          - name: CASSANDRA_DC
            value: {{ .Values.cassandra.env.cassandraDC }}
          - name: CASSANDRA_RACK
            value: {{ .Values.cassandra.env.cassandraRack }}
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "false"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: {{ .Values.cassandra.persistence.data.name }}
          mountPath: {{ .Values.cassandra.persistence.data.mountPath }}
        - name: {{ .Values.cassandra.persistence.commitlog.name }}
          mountPath: {{ .Values.cassandra.persistence.commitlog.mountPath }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.cassandra.persistence.data.name }}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass.name }}
    spec:
      accessModes: [ {{ .Values.cassandra.persistence.data.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.cassandra.persistence.data.size }}
  - metadata:
      name: {{ .Values.cassandra.persistence.commitlog.name }}
      annotations:
        volume.beta.kubernetes.io/storage-class: {{ .Values.storageClass.name }}
    spec:
      accessModes: [ {{ .Values.cassandra.persistence.commitlog.accessMode }} ]
      resources:
        requests:
          storage: {{ .Values.cassandra.persistence.commitlog.size }}
{{- end }}          