#
# Copyright © 2016-2018 The Thingsboard Authors
# Modifications © 2017-2018 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if .Values.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "fullname.fluentdElasticsearch" . }}
  labels:
    app: {{ template "name.fluentdElasticsearch" . }}
    release: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname.fluentdElasticsearch" . }}
  labels:
    app: {{ template "name.fluentdElasticsearch" . }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  - "pods"
  verbs:
  - "get"
  - "watch"
  - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "fullname.fluentdElasticsearch" . }}
  labels:
    app: {{ template "name.fluentdElasticsearch" . }}
    release: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ template "fullname.fluentdElasticsearch" . }}
  namespace: {{ .Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ template "fullname.fluentdElasticsearch" . }}
  apiGroup: ""
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "fullname.fluentdElasticsearch" . }}
  labels:
    app: {{ template "name.fluentdElasticsearch" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name.fluentdElasticsearch" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name.fluentdElasticsearch" . }}
        release: {{ .Release.Name }}
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: {{ template "fullname.fluentdElasticsearch" . }}
      containers:
      - name: {{ template "fullname.fluentdElasticsearch" . }}
        image: "{{ .Values.fluentdElasticsearch.image.repository }}:{{ .Values.fluentdElasticsearch.image.tag }}"
        imagePullPolicy: {{ .Values.fluentdElasticsearch.image.pullPolicy }}
        env:
        - name: FLUENTD_ARGS
          value: --no-supervisor -q
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: {{ .Values.fluentdElasticsearch.dockerContainersPath }}
          readOnly: true
        - name: config-volume
          mountPath: /etc/fluent/config.d
        resources:
{{ toYaml .Values.fluentdElasticsearch.resources | indent 12 }}
    {{- with .Values.fluentdElasticsearch.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.fluentdElasticsearch.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.fluentdElasticsearch.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: {{ .Values.fluentdElasticsearch.dockerContainersPath }}
      - name: config-volume
        configMap:
          name: {{ template "fullname.fluentdElasticsearch" . }}-config
{{- end }}
