apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname.kibana" . }}
  labels:
    app: {{ template "name.kibana" . }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: kibana-ui
      protocol: TCP
      name: kibana-ui
  selector:
    app: {{ template "name.kibana" . }}
    release: {{ .Release.Name }}
